# Generated by Django 5.2.6 on 2025-10-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_body_alter_thread_title'),
        ('forum', '0002_reply_is_deleted_thread_is_deleted_alter_thread_body_and_more'),
    ]

    operations = [
    ]
