# Generated by Django 5.1.1 on 2025-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_is_deleted_thread_is_deleted_alter_thread_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether this reply was posted anonymously'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether this thread was posted anonymously'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
