# Generated by Django 5.1.1 on 2025-10-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_merge_20251006_1714'),
        ('forum', '0003_reply_is_anonymous_thread_is_anonymous_and_more'),
    ]

    operations = [
    ]
