# Generated by Django 5.2.6 on 2025-10-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_merge_20251006_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designates whether this user is banned (soft deleted)'),
        ),
    ]
