# Generated by Django 5.2.6 on 2025-10-13 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.CASCADE, to='forum.thread')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thread_view',
                'ordering': ['-viewed_at'],
                'unique_together': {('user_id', 'thread_id')},
            },
        ),
    ]
