# Generated by Django 5.2.6 on 2025-10-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_user_bio_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(help_text='Encrypted email address', unique=True),
        ),
    ]
