"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment variable for production security
SECRET_KEY = config('SECRET_KEY', default='django-insecure-du72xoqdq=a+8=op+c(r7@g(w@!bml5p$ak7z5gy#q#9iqm@&1')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable to control DEBUG in different environments
DEBUG = config('DEBUG', cast=bool, default=True)

# Allow hosts from environment, fallback to local dev
# For deployment: add ec2-xx-xx-xx-xx.compute-1.amazonaws.com and IP address via .env
ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',  # Django REST Framework for API endpoints
    # Custom apps for Jacaranda Talk forum
    'forum',           # Main forum functionality
    'api',             # RESTful API endpoints
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Custom middleware to exempt API endpoints from CSRF
class DisableCSRFMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        # NOTE: CSRF 校验已启用；保留占位中间件但不再跳过 CSRF。
        return self.get_response(request)

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'forum.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'forum.authentication.EmailBackend',  # Handles both email and username login
]


# HTTPS Configuration (must be defined before using in cookie settings)
# 注意：在配置好 HTTPS 证书之前，应该通过环境变量 FORCE_HTTPS=False 来禁用强制重定向
# 配置 HTTPS 后，可以在 .env 中设置 FORCE_HTTPS=True 来启用
# 这样可以避免在未配置 HTTPS 时返回 HTML 重定向页面而不是 JSON 响应
FORCE_HTTPS = config('FORCE_HTTPS', cast=bool, default=False)

# Session security settings
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = FORCE_HTTPS  # True only when HTTPS is configured
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS & HSTS (enabled in production)
SECURE_SSL_REDIRECT = FORCE_HTTPS  # 只有在配置好 HTTPS 后才启用强制重定向
SECURE_HSTS_SECONDS = 31536000 if FORCE_HTTPS else 0  # 1 year in prod
SECURE_HSTS_INCLUDE_SUBDOMAINS = FORCE_HTTPS
SECURE_HSTS_PRELOAD = FORCE_HTTPS

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email backend for development (stores emails to files for easy parsing)
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'emails'
DEFAULT_FROM_EMAIL = 'no-reply@jacaranda.local'

# Email encryption key (from .env)
EMAIL_ENCRYPTION_KEY = config('EMAIL_ENCRYPTION_KEY', default='')

# Mailjet configuration (from .env)
MAILJET_API_KEY = config('MAILJET_API_KEY', default='')
MAILJET_API_SECRET = config('MAILJET_API_SECRET', default='')
MAILJET_FROM_EMAIL = config('MAILJET_FROM_EMAIL', default=DEFAULT_FROM_EMAIL)
MAILJET_FROM_NAME = config('MAILJET_FROM_NAME', default='Jacaranda Talk')

# Email rate limit (seconds between OTP sends per user)
EMAIL_RATE_LIMIT_SECONDS = config('EMAIL_RATE_LIMIT_SECONDS', default=10, cast=int)

# In-memory cache for OTP storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'jacaranda-cache',
    }
}

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    # Custom exception handler to prevent stack trace exposure
    'EXCEPTION_HANDLER': 'DjangoProject.exception_handler.custom_exception_handler',
}

# CSRF settings for frontend/backend separation
# Development defaults: localhost only
# For deployment: add ec2 domain and IP via .env (e.g., http://ec2-174-129-134-38.compute-1.amazonaws.com,http://174.129.134.38)
DEFAULT_TRUSTED = 'http://localhost:5173,http://127.0.0.1:5173'
CSRF_TRUSTED_ORIGINS = [o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default=DEFAULT_TRUSTED).split(',') if o.strip()]

# CSRF cookies
CSRF_COOKIE_SECURE = FORCE_HTTPS  # True only when HTTPS is configured
CSRF_COOKIE_HTTPONLY = False  # keep readable by frontend if needed for frameworks
CSRF_COOKIE_SAMESITE = 'Lax'
